spring.application.name=inventory-service
server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/inventory
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
# --- Eureka Client Config ---
# The URL of your Eureka Server dashboard
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# Register using IP instead of hostname (recommended for local Docker/Testing)
eureka.instance.prefer-ip-address=true