spring.application.name=springAi
server.port=8080
# Base URL for local Ollama server (default is 11434)
spring.ai.ollama.base-url=http://localhost:11434
# The specific model you have pulled in Ollama (e.g., llama3.2, mistral)
spring.ai.ollama.chat.options.model=tinyllama
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# Register using IP instead of hostname (recommended for local Docker/Testing)
eureka.instance.prefer-ip-address=true